global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'telegram-notifier'  
  routes:  
  - match:
      alertname: SLAViolationInterval  
    receiver: 'telegram-notifier'

# Invio di una alert per la violazione dell'intervallo 
# scelto dall'utente, sempre tramite notifica telegram, 
# e che specifica l'azione correttiva da effettuare o 
# che verrà auto-effettuata.
receivers:
- name: 'telegram-notifier'
  webhook_configs:
  - url: 'http://notification-service:5000/alert'  
    send_resolved: true 
